<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning">A propos de moi</h2>
    <hr>
    <h3><small>Mon PSN : <span class="text-warning">dragon69330</span></small></h3>
</div>

<div class="container">
    <figure class="text-center">
        <img src="../../../Public/www/Views/assets/img/author/me.jpg" alt="Ma photo" class="img-circle wow flipInY" style="width:50%">
        <figcaption>Là c'est moi, Alain</figcaption>
    </figure>

    <hr>

    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h3>Informations Perso</h3>
            <ul class="list-group text-center">
                <li class="list-group-item">Age : 32 ans</li>
                <li class="list-group-item">Permis B</li>
                <li class="list-group-item">3 Enfants à charge</li>
            </ul>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h3>Mes passions</h3>
            <ul class="list-group text-center">
                <li class="list-group-item">Mes enfants</li>
                <li class="list-group-item">Le milieu du web</li>
                <li class="list-group-item">Les MOOC sur le net</li>
                <li class="list-group-item">Le sport en général</li>
                <li class="list-group-item">Le cinéma</li>
                <li class="list-group-item">Certains jeux vidéo.</li>
            </ul>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h3>Actuellement</h3>
            <div class="alert alert-info">
                Je suis en reconversion professionnel dans le milieu du web suite à de grave soucis de santé.
                Ce petit site tout de même assez complet à mon goût me permet de mettre en avant mes connaissances afin qui c'est... de décrocher un poste dans ce domaine.
            </div>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <h3>Les techno. utilisés</h3>
            <ul class="list-group text-center">
                <li class="list-group-item">HTML5</li>
                <li class="list-group-item">CSS3</li>
                <li class="list-group-item">BOOTSTRAP</li>
                <li class="list-group-item">SASS</li>
                <li class="list-group-item">JQUERY</li>
                <li class="list-group-item">PHP</li>
                <li class="list-group-item">MYSQL</li>
            </ul>
        </div>
    </div>            

</div>
