<!-- Page sur les accessoires -->
<div class="jumbotron">
    <h2 class="text-center text-warning wow tada">Listing de tous les accessoires</h2>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row" style="height: 0">
        <div id="affixPerso" style="position: relative; top: 150px">
            <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="200">
                <li class="active"><button type="button" class="btn btn-default" data-toggle="modal" data-target="#search_accs"><i class="fa fa-search" aria-hidden="true"></i> Accs</button></li>
            </ul>

            <!-- Modal -->
            <div class="modal fade" id="search_accs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Rechercher un accessoire</h4>
                        </div>
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                            <legend class="text-warning">Recherche d'un accessoire</legend>
                                <form class="form" action="../Models/result_accs.php" method="POST">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Saisir le nom d'un accessoire.." name="accessory_name">
                                            <div class="input-group-btn">
                                                <button type="submit" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Contenu de la page accessoires -->
<div class="container">
    <div class="row">
        <?php foreach ($info_accs as $value) : ?>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="col-xs-10 col-xs-offset-1 img-thumbnail" id="styleInfo">        
                <div class="title wow slideInLeft" style="top: 70px; left: 10px">
                    <h5><?= $value['name']; ?></h5>
                </div>
                <div class="portrait wow slideInRight">
                    <figure>
                        <img src="../../../Public/www/Views/assets/img/accessories/<?= $value['image']; ?>" alt="Icone de la ressource" class="wow rotateIn img-responsive img-thumbnail">
                    </figure>              
                </div>
                <div class="well" style="opacity: .5; z-index: -1; margin-top: 115px; height: 200px">
                    <legend><small>Effets :</small></legend>
                    <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                </div> <!-- /well -->    
            </div> <!-- / #styleInfo -->
        </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
        <?php endforeach; ?>
    </div> <!-- /row -->
</div> <!-- /container -->
