<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-center text-warning">Combien de monstres faut-il tuer ?</h2>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div>
                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#qts1" aria-controls="qts1" role="tab" data-toggle="tab">0</a></li>
                    <li role="presentation"><a href="#qts2" aria-controls="qts2" role="tab" data-toggle="tab">10</a></li>
                    <li role="presentation"><a href="#qts3" aria-controls="qts3" role="tab" data-toggle="tab">30</a></li>
                    <li role="presentation"><a href="#qts4" aria-controls="qts4" role="tab" data-toggle="tab">50</a></li>
                    <li role="presentation"><a href="#qts5" aria-controls="qts5" role="tab" data-toggle="tab">100</a></li>
                    <li role="presentation"><a href="#qts6" aria-controls="qts6" role="tab" data-toggle="tab">300</a></li>
                    <li role="presentation"><a href="#qts7" aria-controls="qts7" role="tab" data-toggle="tab">500</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <!-- QTS 0 -->
                    <div role="tabpanel" class="tab-pane active" id="qts1">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 0 kill</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_one as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- QTS 10 -->
                    <div role="tabpanel" class="tab-pane" id="qts2">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 10 kills</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_two as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- QTS 30 -->
                    <div role="tabpanel" class="tab-pane" id="qts3">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 30 kills</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_three as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- QTS 50 -->
                    <div role="tabpanel" class="tab-pane" id="qts4">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 50 kills</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_four as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- QTS 100 -->
                    <div role="tabpanel" class="tab-pane" id="qts5">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 100 kill</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_five as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- QTS 300 -->
                    <div role="tabpanel" class="tab-pane" id="qts6">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 300 kills</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_six as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!-- QTS 500 -->
                    <div role="tabpanel" class="tab-pane" id="qts7">
                        <div>
                            <table class="table table-bordered table-hover table-condensed">
                                <caption>Tableau récapitulatif des monstres avec 500 kills</caption>
                                <thead>
                                    <tr>
                                        <th>Nom</th>
                                        <th>Quantités</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($info_amounts_seven as $value) : ?>
                                        <tr>
                                            <td><?= $value['name']; ?></td>
                                            <td><?= $value['amount']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>