<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning">Les armes</h2>    
    <hr>
    <h3><small>Nombre d'armes dans la bdd : 0/200?</h3>
</div>
<div class="container-fluid" style="margin-top:40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title text-center">Nom de l'arme à venir</h3>
                </div>
                <div class="panel-body">
                    Effet de l'arme à venir
                </div>
            </div>
        </div>
    </div>
</div>