<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning wow tada">Les armes</h2>
</div>
<div class="container" style="margin-top:40px">
    <div class="row">
        <legend class="text-center text-info">Doubles lames</legend>
        <?php foreach ($info_arms_7 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/lames/<?= $value['w_image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['w_name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['w_effet']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Épées à une main</legend>
        <?php foreach ($info_arms_8 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/épée/<?= $value['w_image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['w_name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['w_effet']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Épées à 2 mains</legend>
        <?php foreach ($info_arms_9 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/épée_à_2_mains/<?= $value['w_image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['w_name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['w_effet']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Haches</legend>
        <?php foreach ($info_arms_14 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/hache/<?= $value['w_image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['w_name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['w_effet']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Gantelets</legend>
        <?php foreach ($info_arms_5 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Arcs</legend>
        <?php foreach ($info_arms_6 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Cartes</legend>
        <?php foreach ($info_arms_7 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/lames/<?= $value['w_image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['w_name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['w_effet']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Baguettes</legend>
        <?php foreach ($info_arms_8 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Boomerangs</legend>
        <?php foreach ($info_arms_9 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Griffes</legend>
        <?php foreach ($info_arms_10 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">    
        <legend class="text-center text-info">Boucliers</legend>
        <?php foreach ($info_arms_11 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Lances</legend>
        <?php foreach ($info_arms_12 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Évantailles</legend>
        <?php foreach ($info_arms_13 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <hr>
    <div class="row">
        <legend class="text-center text-info">Bouliers</legend>
        <?php foreach ($info_arms_14 as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <div class="panel panel-warning">
                    <div class="panel-heading">
                        <figure class="icone">
                            <img src="../../../Public/www/Views/assets/img/weapons/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 55px" class="wow rotateIn img-thumbnail">
                        </figure>
                        <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                    </div>
                    <div class="panel-body">
                        <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>