<!-- Page d'accueil -->
<div class="jumbotron">
    <h3 class="text-center text-warning">La bataille de la tour : centre</h3>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div>
                <table class="table table-bordered table-hover table-condensed">
                    <caption>Les monstres de la zone</caption>
                    <thead>
                        <tr>
                            <th>Nom du monstre</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($info_bataille_tour_centre as $value) : ?>
                            <tr>
                                <td><?= $value['nom_monstre']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

