<!-- Page d'accueil -->
<div class="jumbotron">
    <h3 class="text-center text-warning">La bataille d'Accordia</h3>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div>
                <table class="table table-bordered table-hover table-condensed">
                    <caption>Les monstres de la zone</caption>
                    <thead>
                        <tr>
                            <th>Monstre</th>
                            <th>Rech.</th>
                            <th>Médail.</th>
                            <th>Exp</th>
                            <th>OR</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($info_bataille_accordia as $value) : ?>
                            <tr>
                                <td><?= $value['nom_monstre']; ?></td>
                                <td><?php 
                                    if($value['nom_monstre'] != "Tyrantosaure" && $value['search'] == 1) 
                                    { 
                                        echo "Oui";
                                    } else {
                                        echo "<span class='text-danger'>Boss</span>";
                                    }
                                ?></td>
                                <td><?php 
                                    if($value['nom_monstre'] != "Tyrantosaure" && $value['medals'] == 1) 
                                    { 
                                        echo "Oui";
                                    } else {
                                        echo "<span class='text-danger'>Boss</span>";
                                    }
                                ?></td>
                                <td><?= $value['exp']; ?></td>
                                <td><?= $value['or']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

