<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning wow tada">Meilleurs zones Libre pour farm de l'or</h2>
</div>
<div class="container" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div id="presentation">
                <p class="wow slideInLeft">Tableau réorganisé par ordre décroissant.</p>
                <hr>
                <p class="wow slideInRight">Le calcul est simple. Sur chaque fiche d'un monstre nous avons son OR. Ainsi je fais une simple addition de chaque type de monstre issu d'une zone spécifique.</p>
                <hr>
                <p class="wow slideInLeft">Une fois le résultat obtenu je l'affiche en brute dans un tableau HTML.</p>
            </div>
            <br />
            <div class="wow fadeIn">
                <legend class="text-warning text-right" style="text-shadow: 0 0 2px #222"><small>Tableau d'xp par zone Libre</small></legend>
                <div class="well" style="opacity: .8; box-shadow: 0 0 5px #222; background-image: url('../../../Public/www/Views/assets/img/parchemin.jpg'); background-size: cover ">                
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th style="color:#eee">Nom de la zone</th>
                                <th style="color:#eee">Or accumulée</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="color:#222">Contreforts du givre</td>
                                <td style="color:#222">3304 <img src="../../../Public/www/Views/assets/img/gold.png" alt="" width="5%"></td>
                            </tr>
                            <tr>
                                <td style="color:#222">Le Bois ténébreux</td>
                                <td style="color:#222">2902</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Terres brûlées</td>
                                <td style="color:#222">2868</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Contreforts du givre funèbre</td>
                                <td style="color:#222">2552</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Aux Terres mortes</td>
                                <td style="color:#222">2389</td>
                            </tr>
                            <tr>
                                <td style="color:#222">A la Passe noire</td>
                                <td style="color:#222">2247</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Plaine verdoyante</td>
                                <td style="color:#222">1968</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Passe rouge</td>
                                <td style="color:#222">1968</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Les Dunes damnées</td>
                                <td style="color:#222">1949</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Plaine sinistré</td>
                                <td style="color:#222">1804</td>
                            </tr>
                            <tr>
                                <td style="color:#222">La forêt des Madriers</td>
                                <td style="color:#222">979</td>
                            </tr>
                            <tr>
                                <td style="color:#222">Déserg</td>
                                <td style="color:#222">174</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>