<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-center text-warning">Me contacter</h2>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="alert alert-danger">
                Non fonctionnel pour le moment
            </div>
            <div class="alert alert-info">
                <h4>Pourquoi me contacter ?</h4>
                <hr>
                - Vous avez détecté un bug ?<br />
                - Vous trouvez qu'il manque quelque chose au listing ?<br />
                - Un objets manquant ?<br />
                - Une donnée sur un monstre absent ?<br />
                - Une faute d'orthographe ?
                - Autre chose ?
                <hr>
                Faîtes le moi savoir en remplissant le formulaire ci-dessous
            </div>
            <form action="" method="post">
                <input type="text" class="form-control" id="email" placeholder="Votre email"><br />
                <select class="form-control">
                    <option>Il manque quelque chose</option>
                    <option>J'ai découvert un bug</option>
                    <option>Quelques fautes à corriger</option>
                    <option>Autre</option>
                </select><br />                
                <textarea class="form-control" rows="6" placeholder="Veuillez saisir votre message ici.. Je m'enfou des fautes d'orthographes par contre veuillez être le plus précis possible. Merci pour votre contribution"></textarea>
                <hr>
                <button type="submit" class="btn btn-primary" disabled>Envoyer</button> 
                <button type="clear" class="btn btn-default" disabled>Effacer</button>
            </form>
        </div>
    </div>
</div>