<!-- Page full mobs -->
<div class="jumbotron">
    <h2 class="text-center text-warning">Listing de tous les monstres</h2>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row" style="height: 0">
        <div id="affixPerso" style="position: relative; top: 150px">
            <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="200">
                <li class="active"><button type="button" class="btn btn-default" data-toggle="modal" data-target="#search_mobs"><i class="fa fa-search" aria-hidden="true"></i> Mob</button></li>
            </ul>

            <!-- Modal -->
            <div class="modal fade" id="search_mobs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Rechercher un monstre</h4>
                        </div>
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                            <legend class="text-warning">Recherche d'un monstre</legend>
                            <form class="form" action="../Models/result_mobs.php" method="POST">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Saisir le nom d'un monstre" name="monster_name">
                                        <div class="input-group-btn">
                                            <button type="submit" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Contenu de la page full mobs -->
<div class="container">
    <div class="row">
        <?php foreach ($info_mobs as $value) : ?>
        <div class="col-xs-12 col-md-6 col-lg-4">
            <div class="col-xs-10 col-xs-offset-1 box" id="styleInfo">        
                <div class="title wow slideInLeft">
                    <h5><?= $value['m_name']; ?></h5>
                </div>
                <div class="ribbon"><span>QTS : <?= $value["m_amount"]; ?></span></div>
                <div class="portrait wow slideInRight">
                    <?php if ($value['m_search'] == 0 ) : ?>
                        <figure>
                            <img src="../../../Public/www/Views/assets/img/monsters/<?= $value['m_image']; ?>" alt="" class="img-thumbnail">
                        </figure>
                    <?php else : ?>
                        <figure>
                            <img src="../../../Public/www/Views/assets/img/monsters/<?= $value['m_image']; ?>" alt="" class="img-thumbnail">
                        </figure>
                        <figcaption class="text-center"><small class="label label-warning"><span class="text-warning">En fuite...</span></small></figcaption>
                    <?php endif; ?>                    
                </div>
                <div class="well" style="opacity: .5; z-index: -1">
                    <legend><small>Vous gagnerez :</small></legend>
                    <table class="table text-center table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>Expérience</th>
                                <th>Or</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><span class="badge wow fadeIn"><?= $value["m_exp"]; ?></span></td>
                                <td><span class="badge wow fadeIn"><?= $value["m_gold"]; ?></span></td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- /well -->
                <?php if ($value['medal_image'] === NULL) : ?>
                    <figure class="medals wow tada hidden-xs hidden-sm hidden-md hidden-lg"></figure>
                <?php else : ?>
                    <figure class="medals wow tada">
                        <img src="../../../Public/www/Views/assets/img/medals/<?= $value['medal_image']; ?>" alt="image de la médaille" class="img-circle">
                    </figure>
                <?php endif; ?>               
            </div> <!-- / #styleInfo -->
        </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
        <?php endforeach; ?>
    </div> <!-- /row -->
</div> <!-- /container -->
