<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning wow tada">Accueil</h2>
</div>
<div class="container" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.jpg'); background-size: cover ">
                <legend class="text-warning text-right" style="text-shadow: 0 0 2px #222"><small>Moteur de recherche rapide</small></legend>
                <form class="form">
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="EN DÉVELOPPEMENT..." id="inputSearch" disabled="disabled">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default" disabled="disabled"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div id="presentation">
                <p class="wow slideInLeft">Dragon Quest Heroes 2 est un jeu prenant. mais il faut l'avoué, si on est pas un minimum organisé, rechercher un type de monstre spécifique est assez casse gueule.</p>
                <hr>
                <p class="wow slideInRight">En effet, il faut parcourir chaque map, noter sur une feuille de papier le loot/monstre... Je ne vous le cache pas, c'est très long et certains n'auront pas la patience d'allez jusqu'au bout.</p>
                <hr>
                <p class="wow slideInLeft">C'est pour celà que j'ai tenu à rédigé ce site 'perso' afin d'aider un très grand nombre de personne.</p>
                <hr>
                <p class="wow slideInUp">G un grand "G" comme gratuit. Et oui ce que je propose reste entièrement gratuit. Il est hors de question de faire du profit sur ce site. La seule chose qui m'intéresse c'est la possibilité de proposer mon projet pour un futur emploi.</p>
            </div>
        </div>
    </div>
</div>