<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning">Accueil</h2>
</div>
<div class="container-fluid" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="alert alert-warning">
                Projet open-source : <a href="https://github.com/Zyrass/project-perso-dqh2">Lien ici</a><br />
                <small>Donnée en local uniquement</small>
            </div>
            <div id="presentation">
                <p>Dragon Quest Heroes 2 est un jeu prenant. mais il faut l'avoué, si on est pas un minimum organisé, rechercher un type de monstre spécifique est assez casse gueule.<br /><br />
                En effet, il faut parcourir chaque map, noter sur une feuille de papier le loot/monstre... Je ne vous le cache pas, c'est très long et certains n'auront pas la patience d'allez jusqu'au bout.<br /><br />
                C'est pour celà que j'ai tenu à rédigé ce site 'perso' afin d'aider un très grand nombre de personne. Le tout gratuitement !!</p>
                <div class="alert alert-danger">
                    <p>/!\ Il est uniquement adapté pour mobile au delà je m'en occupe pas pour le moment dans le sens ou devant la télé avec son téléphonne portable c'est bien plus pratique. Mais plus tard viendons la version tablette et PC.</p>
                </div>
            </div>
            <div class="alert alert-info">
                <h4>A venir...</h4>
                <hr>
                <ul>
                    <li>Moteur de recherche</li>
                    <li>Ajout des icônes du jeu</li>
                    <li>Ajout d'animation</li>
                    <li>Version tablette &amp; PC</li>
                </ul>
            </div>
        </div>
    </div>
</div>