<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning">Accueil</h2>
</div>
<div class="container-fluid" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div id="presentation">
                <p>Dragon Quest Heroes 2 est un jeu prenant. mais il faut l'avoué, si on est pas un minimum organisé, rechercher un type de monstre spécifique est assez casse gueule.<br /><br />
                En effet, il faut parcourir chaque map, noter sur une feuille de papier le loot/monstre... Je ne vous le cache pas, c'est très long et certains n'auront pas la patience d'allez jusqu'au bout.<br /><br />
                C'est pour celà que j'ai tenu à rédigé ce site 'perso' afin d'aider un très grand nombre de personne.</p>
            </div>
        </div>
    </div>
</div>