<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-center text-warning wow tada">Les ingrédients</h2>
</div>

<div class="container" style="margin-top: 40px">
    <div class="row">
    <?php foreach ($info_ingredients as $value) : ?>
        <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <figure class="icone">
                        <img src="../../../Public/www/Views/assets/img/ingredients/<?= $value['img']; ?>" alt="Icone de la ressource" style="width:50px" class="wow rotateIn">
                    </figure>
                    <h3 class="text-right wow fadeIn"><small><?= $value['name']; ?></small></h3>                    
                </div>
                <div class="panel-body">
                    <h6>On peut en obtenir sur :</h6>
                    <ul class="list-group">
                        <?php foreach($info_loot as $value) : ?>
                            <li class="list-group-item">
                                <img src="../../../Public/www/Views/assets/img/monsters/<?= $value['image_monster']; ?>" alt="image du monstre" style="width:15%" class="wow rotateOut">
                                <span class="pull-right"><?= $value['name_monster']; ?></span>
                            </li>
                        <?php endforeach; ?>
                    </ul>                        
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
</div>