<!-- Page Ingrédients -->
<div class="jumbotron">
    <h2 class="text-center text-warning wow tada">Listing de tous les ingrédients</h2>
</div>

<div class="container-fluid" style="margin-top: 40px">
    <div class="row" style="height: 0">
        <div id="affixPerso" style="position: relative; top: 150px">
            <ul class="nav nav-pills nav-stacked" data-spy="affix" data-offset-top="200">
                <li class="active"><button type="button" class="btn btn-default" data-toggle="modal" data-target="#search_ingre"><i class="fa fa-search" aria-hidden="true"></i> Ress</button></li>
            </ul>

            <!-- Modal -->
            <div class="modal fade" id="search_ingre" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Rechercher un ingrédient</h4>
                        </div>
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                                <form class="form" action="../Models/result_ingre.php" method="POST">
                                    <div class="form-group">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Saisir le nom d'un ingrédient.." name="ingredient_name">
                                            <div class="input-group-btn">
                                                <button type="submit" class="btn btn-default"><i class="fa fa-search" aria-hidden="true"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Contenu de la page full ingrédients -->
<div class="container">
    <div class="row">
        <?php foreach ($info_all_loot as $value) : ?>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="col-xs-10 col-xs-offset-1 img-thumbnail" id="styleInfo" style="height: 250px; box-shadow: 0 0 5px #222">
                    <div class="thumbnail" style="opacity: .8; margin-top:20px; box-shadow: 0 0 5px #222;">
                        <figure class="text-center">
                            <img src="../../../Public/www/Views/assets/img/ingredients/<?= $value['img']; ?>" alt="Icone de la ressource" class="wow fadeIn" >
                        </figure>
                    </div>
                    <div class="title" style="top: 190px; left: 10px">
                        <h5 class="wow fadeIn"><?= $value['name']; ?></h5>
                    </div>
                </div> <!-- / #styleInfo -->
            </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
        <?php endforeach; ?>
    </div> <!-- /row -->
</div> <!-- /container -->




