<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning wow tada">Listing des médailles</h2>
</div>

<!-- Contenu de la page medals -->
<div class="container" style="margin-top: 40px">
    <div class="row">

        <div class="col-xs-12">
            <div class="well well-sm" style="height:120px">
                <legend><small>Choix du type de médaille</small></legend>
                <form action="" method="post">
                    <div class="col-xs-10">
                        <select class="form-control pull-left" name="choices">
                            <option value="1">Toutes les médailles</option>
                            <option value="2">Sentinelle</option>
                            <option value="3">Remplaçant</option>
                            <option value="4">Escorte</option>
                        </select>
                    </div>
                    <div class="col-xs-2">
                        <input type="submit" class="btn btn-warning btn-block" value="Go"/>
                    </div>
                </form>
            </div>
        </div>

        <?php if(isset($_POST['choices']) && $_POST['choices'] == 1) : ?>
            
            <!-- Toutes les médailles --> 
                <?php foreach ($info_medals_all as $result_info) : ?>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                        <div class="col-xs-10 col-xs-offset-1 img-thumbnail" id="styleInfo" style="height: 250px; box-shadow: 0 0 5px #222">
                            <div class="thumbnail" style="opacity: .5; margin-top:20px; box-shadow: 0 0 5px #222;">
                                <figure class="text-center">
                                    <img src="../../../Public/www/Views/assets/img/medals/<?= $result_info['image']; ?>" alt="Icone de la ressource" class="wow rotateIn" >
                                </figure>
                            </div>
                            <div class="title" style="top: 190px">
                                <h5 class="wow slideInRight"><?= $result_info['name']; ?></h5>
                            </div>
                        </div> <!-- / #styleInfo -->
                    </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
                <?php endforeach; ?>  

        <?php elseif(isset($_POST['choices']) && $_POST['choices'] == 2) : ?>
        
            <!-- Les médailles de type sentinelle --> 
                <?php foreach ($info_medals_sentinelle as $result_info) : ?>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                        <div class="col-xs-10 col-xs-offset-1 img-thumbnail" id="styleInfo" style="height: 250px; box-shadow: 0 0 5px #222">
                            <div class="thumbnail" style="opacity: .5; margin-top:20px; box-shadow: 0 0 5px #222;">
                                <figure class="text-center">
                                    <img src="../../../Public/www/Views/assets/img/medals/<?= $result_info['image']; ?>" alt="Icone de la ressource" class="wow rotateIn" >
                                </figure>
                            </div>
                            <div class="title" style="top: 190px">
                                <h5 class="wow slideInRight"><?= $result_info['name']; ?></h5>
                            </div>
                        </div> <!-- / #styleInfo -->
                    </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
                <?php endforeach; ?>  

        <?php elseif(isset($_POST['choices']) && $_POST['choices'] == 3) : ?>

            <!-- Les médailles de type remplaçant --> 
                <?php foreach ($info_medals_remplaçant as $result_info) : ?>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                        <div class="col-xs-10 col-xs-offset-1 img-thumbnail" id="styleInfo" style="height: 250px; box-shadow: 0 0 5px #222">
                            <div class="thumbnail" style="opacity: .5; margin-top:20px; box-shadow: 0 0 5px #222;">
                                <figure class="text-center">
                                    <img src="../../../Public/www/Views/assets/img/medals/<?= $result_info['image']; ?>" alt="Icone de la ressource" class="wow rotateIn" >
                                </figure>
                            </div>
                            <div class="title" style="top: 190px">
                                <h5 class="wow slideInRight"><?= $result_info['name']; ?></h5>
                            </div>
                        </div> <!-- / #styleInfo -->
                    </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
                <?php endforeach; ?>  

        <?php elseif(isset($_POST['choices']) && $_POST['choices'] == 4) : ?>

            <!-- Les médailles de type escorte --> 
                <?php foreach ($info_medals_escorte as $result_info) : ?>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                        <div class="col-xs-10 col-xs-offset-1 img-thumbnail" id="styleInfo" style="height: 250px; box-shadow: 0 0 5px #222">
                            <div class="thumbnail" style="opacity: .5; margin-top:20px; box-shadow: 0 0 5px #222;">
                                <figure class="text-center">
                                    <img src="../../../Public/www/Views/assets/img/medals/<?= $result_info['image']; ?>" alt="Icone de la ressource" class="wow rotateIn" >
                                </figure>
                            </div>
                            <div class="title" style="top: 190px">
                                <h5 class="wow slideInRight"><?= $result_info['name']; ?></h5>
                            </div>
                        </div> <!-- / #styleInfo -->
                    </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
                <?php endforeach; ?>                    

        <?php endif; ?>
    </div>
</div>