<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-center text-warning">Expérience par monstres</h2>
</div>
<div>
    <table class="table table-bordered table-hover table-condensed">
        <caption>Tableau récapitulatif des monstres avec l'expérience associé</caption>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Expérience</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($info_mobs_xp as $value) : ?>
                <tr>
                    <td><?= $value['name']; ?></td>
                    <td><?= $value['experience']; ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>