<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning">Les orbes</h2>
</div>
<div class="container-fluid" style="margin-top:40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <?php foreach ($info_orbs as $value) : ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <figure class="icone">
                        <img src="../../../Public/www/Views/assets/img/orbs/<?= $value['image']; ?>" alt="image représentant une orbe" style="width: 50px">
                    </figure>
                    <h3 class="text-right"><small><?= $value['name']; ?></small></h3>                    
                </div>
                <div class="panel-body">
                    <small><?= $value['effect']; ?></small>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>