<!-- Page Ingrédients -->
<div class="jumbotron">
    <h2 class="text-center text-warning wow tada">Les orbes</h2>
</div>

<!-- Contenu de la page full mobs -->
<div class="container">
    <div class="row">
        <?php foreach ($info_orbs as $value) : ?>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="col-xs-10 col-xs-offset-1" id="styleInfo">        
                <div class="title wow slideInLeft" style="top: 70px">
                    <h5><?= $value['name']; ?></h5>
                </div>
                <div class="portrait wow slideInRight">
                    <figure>
                        <img src="../../../Public/www/Views/assets/img/orbs/<?= $value['image']; ?>" alt="Icone de la ressource" class="wow rotateIn img-responsive">
                    </figure>              
                </div>
                <div class="well" style="opacity: .5; z-index: -1; margin-top: 130px">
                    <legend><small>Effets :</small></legend>
                    <span class="wow fadeIn"><small><?= $value['effect']; ?></small></span>
                </div> <!-- /well -->    
            </div> <!-- / #styleInfo -->
        </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
        <?php endforeach; ?>
    </div> <!-- /row -->
</div> <!-- /container -->
