<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning wow tada">Trouvez facilement des "Valgues"</h2>
</div>
<div class="container" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                <legend class="text-warning text-right" style="text-shadow: 0 0 2px #222"><small>Mais où trouver la ressource "Valgue"</small></legend>
                <div id="presentation" style="color: #222">
                    <p class="wow slideInLeft">La ressource "Valgue" n'est pas une ressource qui se drop/loot sur un monstre.</p>
                    <p class="wow slideInRight">Elle se trouve dans la plaine verdoyante et pour pouvoir en obtenir il faut au préalable avoir dans son équipe "Olivier" afin d'abaisser le TRONC d'arbre qui bloque le chemin vers un bout de terre.</p>
                    <p class="wow slideInLeft">Une fois l'arbre faisant office de pont, vous aurez quelques mobs sans importance qui seront là pour vous mettre en charpie, mais surtout, vous aurez 3 gisements qui pop régulièrement avec notre ressource tant convoité</p>
                    <br />
                    <figure class="text-center">
                        <img src="../../../Public/www/Views/assets/img/cheat/search-valgue.webp" alt="entrée pour la ressource valgue" class="img-thumbnail img-responsive">
                    </figure>
                </div>
            </div>

        </div>
    </div>
</div>