<!-- Page d'accueil -->
<div class="jumbotron">
    <h3 class="text-center text-warning">Aux Terres mortes</h3>
</div>

<!-- Contenu de la page full mobs -->
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Gain d'XP et d'OR</small></legend>
                <p>Si vous tuer un seul monstre de chaque espèce dans cette zone vous gagnerez : <span class="text-warning"><?= $info_bataille_count->s_exp; ?></span>pts d'xp et <span class="text-warning"><?= $info_bataille_count->s_gold; ?></span> or !</p>
            </div>
        </div>
    </div>
    <div class="row">
        <?php foreach ($info_bataille as $value) : ?>
        <div class="col-xs-12 col-md-6 col-lg-4">
            <div class="col-xs-10 col-xs-offset-1 box" id="styleInfo">        
                <div class="title wow slideInLeft">
                    <h5><?= $value['m_name']; ?></h5>
                </div>
                <div class="ribbon"><span>QTS : <?= $value["a_amount"]; ?></span></div>
                <div class="portrait wow slideInRight">
                    <?php if ($value['m_search'] === 0 ) : ?>
                        <figure>
                            <img src="../../../Public/www/Views/assets/img/monsters/<?= $value['m_image']; ?>" alt="" class="img-thumbnail">
                        </figure>
                    <?php else : ?>
                        <figure>
                            <img src="../../../Public/www/Views/assets/img/monsters/<?= $value['m_image']; ?>" alt="" class="img-thumbnail">
                        </figure>
                        <figcaption class="text-center"><small class="label label-warning"><span class="text-warning">En fuite...</span></small></figcaption>
                    <?php endif; ?>                    
                </div>
                <div class="well" style="opacity: .5; z-index: -1">
                    <legend><small>Vous gagnerez :</small></legend>
                    <table class="table text-center table-bordered table-condensed">
                        <thead>
                            <tr>
                                <th>Expérience</th>
                                <th>Or</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><span class="badge wow fadeIn"><?= $value["m_exp"]; ?></span></td>
                                <td><span class="badge wow fadeIn"><?= $value["m_gold"]; ?></span></td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- /well -->
                <?php if ($value['medal_image'] === NULL) : ?>
                    <figure class="medals wow tada hidden-xs hidden-sm hidden-md hidden-lg"></figure>
                <?php else : ?>
                    <figure class="medals wow tada">
                        <img src="../../../Public/www/Views/assets/img/medals/<?= $value['medal_image']; ?>" alt="??" class="img-circle">
                    </figure>
                <?php endif; ?>               
            </div> <!-- / #styleInfo -->
        </div> <!-- /col-xs-12 col-md-6 col-lg-4 -->
        <?php endforeach; ?>
    </div> <!-- /row -->
</div> <!-- /container -->
