<!-- Page sur la découverte de l'emplacement de chaque trésors -->
<div class="jumbotron">
    <h2 class="text-warning">Où sont les trésors ?</h2>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">        
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>La Plaine verdoyante</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x7 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/1.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal1">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Le Déserg</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x12 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/2.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal2">
                        </figure>    
                    </div>   
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>La Forêt des madriers</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x10 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/3.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal3">
                        </figure>    
                    </div> 
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>La Passe rouge</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x7 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/4.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal4">
                        </figure>    
                    </div> 
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Les Terres brûlées</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x13 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/5.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal5">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Les Contreforts de givre</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x13 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/6.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal6">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>La Plaine sinistre</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x7 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/7.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal7">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Les Dunes damnées</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x11 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/8.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal8">
                        </figure>    
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Les Bois ténébreux</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x11 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/9.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal9">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>La Passe noire</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x7 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/10.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal10">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Les Terres mortes</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x12 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/11.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal11">
                        </figure>    
                    </div>
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-lg-2">
                    <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                        <legend class="text-warning text-left" style="text-shadow: 0 0 2px #222"><small>Contreforts funèbres</small></legend>
                        <figure>
                            <figcaption class="text-center" style="color: #eee"><small>x15 <img src="../../../Public/www/Views/assets/img/chest.webp" alt="image d'un coffre" width="8%"> à retrouver</small></figcaption>
                            <img src="../../../Public/www/Views/assets/img/treasures/12.webp" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal12">
                        </figure>    
                    </div>
                </div>
            </div>
            


            <!-- Modal : La Plaine verdoyante -->
            <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/1.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Le Déserg -->
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/2.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La forêt des madriers -->
            <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/3.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La Passe rouge -->
            <div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/4.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Terres brûlées -->
            <div class="modal fade" id="myModal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/5.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Contreforts de givre -->
            <div class="modal fade" id="myModal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/6.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La Plaine sinistre -->
            <div class="modal fade" id="myModal7" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/7.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Dunes damnées -->
            <div class="modal fade" id="myModal8" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/8.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Bois ténébreux -->
            <div class="modal fade" id="myModal9" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/9.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La Passe noire -->
            <div class="modal fade" id="myModal10" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/10.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Terres mortes -->
            <div class="modal fade" id="myModal11" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/11.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Contreforts funèbres -->
            <div class="modal fade" id="myModal12" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-cover">
                        <div class="modal-body" style="background-image: url('../../../Public/www/Views/assets/img/parchemin.webp'); background-size: cover ">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/12.webp" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
