<!-- Page sur la découverte de l'emplacement de chaque trésors -->
<div class="jumbotron">
    <h2 class="text-warning">Où sont les trésors ?</h2>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>La Plaine verdoyante</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/1.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal1">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Le Déserg</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/2.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal2">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>La Forêt des madriers</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/3.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal3">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>La Passe rouge</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/4.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal4">
                    </figure>    
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Les Terres brûlées</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/5.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal5">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Les Contreforts de givre</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/6.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal6">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>La Plaine sinistre</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/7.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal7">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Les Dunes damnées</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/8.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal8">
                    </figure>    
                </div>
            </div>
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Les Bois ténébreux</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/9.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal9">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>La Passe noire</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/10.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal10">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Les Terres mortes</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/11.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal11">
                    </figure>    
                </div>
                <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-md-2">
                    <figure>
                        <figcaption><h6><small>Contreforts funèbres</small></h6></figcaption>
                        <img src="../../../Public/www/Views/assets/img/treasures/12.png" alt="miniature" class="img-responsive"  data-toggle="modal" data-target="#myModal12">
                    </figure>    
                </div>
            </div>


  
            


            <!-- Modal : La Plaine verdoyante -->
            <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">La Plaine verdoyante</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/1.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Le Déserg -->
            <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Le Déserg</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/2.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La forêt des madriers -->
            <div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">La forêt des madriers</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/3.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La Passe rouge -->
            <div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">La Passe rouge</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/4.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Terres brûlées -->
            <div class="modal fade" id="myModal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Les Terres brûlées</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/5.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Contreforts de givre -->
            <div class="modal fade" id="myModal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Les Contreforts de givre</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/6.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La Plaine sinistre -->
            <div class="modal fade" id="myModal7" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">La Plaine sinistre</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/7.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Dunes damnées -->
            <div class="modal fade" id="myModal8" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Les Dunes damnées</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/8.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Bois ténébreux -->
            <div class="modal fade" id="myModal9" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Les Bois ténébreux</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/9.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : La Passe noire -->
            <div class="modal fade" id="myModal10" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">La Passe noire</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/10.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Les Terres mortes -->
            <div class="modal fade" id="myModal11" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Les Terres mortes</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/11.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal : Contreforts funèbres -->
            <div class="modal fade" id="myModal12" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Contreforts funèbres</h4>
                        </div>
                        <div class="modal-body">
                            <figure>
                                <img src="../../../Public/www/Views/assets/img/treasures/12.png" alt="Image pour retrouver chaque trésor" class="img-responsive">
                            </figure>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
