<!-- Page d'accueil -->
<div class="jumbotron">
    <h2 class="text-warning wow tada">En cours de développement</h2>
</div>
<div class="container" style="margin-top: 40px">
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
            <div class="well well-lg wow fadeIn" style="background-image: url('../../../Public/www/Views/assets/img/spec_bg_pc.webp'); background-size: cover ">
                <legend class="text-warning text-right" style="text-shadow: 1px 1px #eee"><small>Voici la liste des choses qui sont en cours de développement</small></legend>
                <ul class="list-group">
                    <li class="list-group-item">- <s>Optimisation de toutes les images avec le format ".webp"</s> <span class="label label-danger">Priorité très haute</span></li>
                    <li class="list-group-item">- Ajout des informations sur les 2 accessoires inconnu <span class="label label-danger">Priorité très haute</span></li>
                    <li class="list-group-item">- <s>Ajout dans les bonus d'une astuce pour trouver la ressource rare : "Valgue"</s> <span class="label label-danger">Priorité très haute</span></li>
                    <li class="list-group-item">- Ajout + création des 3 images des monstres que je n'ai pas encore battu <span class="label label-danger">Priorité très haute</span></li>
                    <li class="list-group-item">- <s>Optimisation de l'interface des médailles sur toutes les tailles d'écran</s> <span class="label label-danger">Priorité très haute</span></li>
                    <li class="list-group-item">- <s>Ajout dans chaque zone d'xp l'or et l'xp gagnez sur un seul monstre de chaque</s> (Comme la Plaine verdoyante)<span class="label label-danger">Priorité très haute</span></li>
                    <li class="list-group-item">- <s>Conception d'une page sur un classement par rapport aux zones en fonction de l'xp gagné sur un monstre de chaque</s> <span class="label label-warning">Priorité haute</span></li>
                    <li class="list-group-item">- <s>Conception d'une page sur un classement par rapport aux zones en fonction de l'or gagné sur un monstre de chaque</s> <span class="label label-warning">Priorité haute</span></li>
                    <li class="list-group-item">- Conception de la page "Contact" afin de m'envoyer des informations bug ou autre.<span class="label label-warning">Priorité haute</span></li>
                    <li class="list-group-item">- Moteur de recherche en page d'accueil <span class="label label-success">Priorité normal</span></li>
                    <li class="list-group-item">- Ajout de plusieurs informations trouvé sur le web par-ci par-là.<span class="label label-success">Priorité normal</span></li>
                    <li class="list-group-item">- Ajout dans la liste des ingrédients la liste des monstres qui permettent d'obtenir cette ressources spécifique <span class="label label-success">Priorité normal</span></li>
                    <li class="list-group-item">- <s>Optimisation de l'interface de la page sur la découverte de l'emplacement des trésors</s> <span class="label label-info">Priorité faible</span></li>
                    <li class="list-group-item">- Conception de la page "A propos de moi" afin de me connaître.<span class="label label-default">Priorité très faible</span></li>
                    <li class="list-group-item">- Conception de la page "Livre d'or'" afin de laisser un petit message si vous le souhaitez.<span class="label label-default">Priorité très faible</span></li>
                    <li class="list-group-item">- Ajout de quelques animations supplémentaire.<span class="label label-default">Priorité très faible</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>